train:
  model: "mel2f0"
  seed: 1234
  epochs: 10000
  learning_rate: 1e-6
  betas: [0.9, 0.99]
  lr_decay: 0.98
  total_steps: 100 # base on dataset size
  eps: 1e-9
  batch_size: 64
#############################
log:
  info_interval: 100
  eval_interval: 10
  save_interval: 100

